name: Build and Test
 
on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  actions: read
  checks: write
  contents: none
  deployments: none
  id-token: write
  issues: none
  packages: none
  pull-requests: write
  repository-projects: none
  security-events: write
  statuses: write

jobs:
  pnpm-base-test:
    strategy:
      matrix:
        node-version: [18.x, 20.x]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: pnpm/action-setup@v3
        name: Install pnpm
        id: pnpm-install
        with:
          version: latest
          run_install: |
            - recursive: false
              args: [--no-frozen-lockfile]

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4.0.2
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true

      - name: Build
        if: matrix.targets.lint == true
        env:
          NEXT_PUBLIC_AUTH0_DOMAIN: test
          NEXT_PUBLIC_AUTH0_CLIENT_ID: test
          NEXT_PUBLIC_CALLBACK_URL: http://localhost:3000
        run: pnpm lint --fix && pnpm build
